version: '3'
services:
  workspace:
    image: haxe/haxelib_devcontainer_workspace:development
    init: true
    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock
      - ..:/workspace:cached
    environment:
      - HAXELIB_SERVER=haxelib
      - HAXELIB_SERVER_PORT=80
      - HAXELIB_DB_HOST=dbHost
      - HAXELIB_DB_PORT=3306
      - HAXELIB_DB_USER=dbUser
      - HAXELIB_DB_PASS=dbPass
      - HAXELIB_DB_NAME=haxelib
      - EARTHLY_BUILDKIT_HOST=tcp://earthly:8372
      - EARTHLY_SECRET_FILES=.envrc=/workspace/.envrc
      - EARTHLY_USE_INLINE_CACHE=true
      - EARTHLY_SAVE_INLINE_CACHE=true
    user: vscode
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity
  # haxelib:
  #   build: ..
  #   ports:
  #     - "80:80"
  #   environment:
  #     - HAXELIB_DB_HOST=dbHost
  #     - HAXELIB_DB_PORT=3306
  #     - HAXELIB_DB_USER=dbUser
  #     - HAXELIB_DB_PASS=dbPass
  #     - HAXELIB_DB_NAME=haxelib
  #   volumes:
  #     - ../www:/var/www/html
  dbHost:
    image: mariadb:10.5
    environment:
      - TZ=UTC
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=haxelib
      - MYSQL_USER=dbUser
      - MYSQL_PASSWORD=dbPass
    ports:
      - "3306:3306"
    restart: unless-stopped
  earthly:
    image: earthly/buildkitd:v0.6.2
    privileged: true
    environment:
      - BUILDKIT_TCP_TRANSPORT_ENABLED=true
    expose:
      - 8372
    volumes:
      # https://docs.earthly.dev/docs/guides/using-the-earthly-docker-images/buildkit-standalone#earthly_tmp_dir
      - earthly-tmp:/tmp/earthly:rw

volumes:
  earthly-tmp:
