name: CI-prod

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy-prod:
    concurrency: deploy
    runs-on: ubuntu-latest
    container: haxe/haxelib_devcontainer_workspace:20210928094749
    env:
      AWS_DEFAULT_REGION: eu-west-1
      TF_INPUT: 0
      TF_IN_AUTOMATION: 1
    steps:
      # make sure the image exists
      - run: docker manifest inspect haxe/lib.haxe.org:${{ github.sha }}
      - uses: actions/checkout@v2
      - run: terraform init
        working-directory: terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: terraform apply -auto-approve
        working-directory: terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_HAXELIB_DB_PASS: ${{ secrets.TF_VAR_HAXELIB_DB_PASS }}
          TF_VAR_HAXELIB_SERVER_IMAGE_MASTER: haxe/lib.haxe.org:${{ github.sha }}
