name: CI

on:
  push:
    branches:
      - development
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Haxe
        run: |
          set -ex
          sudo add-apt-repository ppa:haxe/haxe3.4 -y
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y neko haxe
      - run: neko run.n setup haxelib_global
      - run: haxe libs.hxml
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: haxeci
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: haxe/lib.haxe.org:${{ github.sha }}
