name: CI

on:
  push:
    branches:
      - development
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and export
        uses: docker/build-push-action@v2
        with:
          tags: haxe/lib.haxe.org:${{ github.sha }}
          outputs: type=docker,dest=/tmp/haxelib-server-image.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: haxelib-server-image
          path: /tmp/haxelib-server-image.tar
  push:
    needs: build
    if: success() && ( github.event_name == 'push' ) && ( github.ref == 'refs/heads/development' ) && ( github.repository == 'HaxeFoundation/haxelib' )
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: haxelib-server-image
          path: /tmp
      - name: Load image
        run: docker load --input /tmp/haxelib-server-image.tar
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: haxeci
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image
        run: docker push haxe/lib.haxe.org:${{ github.sha }}
